"""change datatype to time

Revision ID: 1055cc89ddb5
Revises: 
Create Date: 2024-12-12 09:54:38.520792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1055cc89ddb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Time(),
               postgresql_using="start_time::time without time zone",  # Hướng dẫn PostgreSQL cách chuyển đổi
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=20),
               postgresql_using="start_time::time without time zone",
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
