"""Create department table

Revision ID: 15a7478e9c9c
Revises: 1055cc89ddb5
Create Date: 2024-12-17 14:14:19.486604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a7478e9c9c'
down_revision = '1055cc89ddb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_booking_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'booking', ['booking_id'], ['booking_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_booking_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
