"""Add holidays table

Revision ID: 1f449fb5d340
Revises: 98eeb68940c0
Create Date: 2025-01-10 09:11:48.639169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f449fb5d340'
down_revision = '98eeb68940c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('h_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.drop_column('h_date')

    # ### end Alembic commands ###
