"""Edit holidays table

Revision ID: f3b92399ca49
Revises: 1f449fb5d340
Create Date: 2025-01-10 10:25:05.945298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b92399ca49'
down_revision = '1f449fb5d340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.drop_constraint('holiday_h_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.create_unique_constraint('holiday_h_name_key', ['h_name'])

    # ### end Alembic commands ###
